name: Integration
on:
  - pull_request
  - push
jobs:
  csharp:
    name: CSharp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/Generator/integration/csharp
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Run
        run: bin/Release/net6.0/test
  go:
    name: Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/Generator/integration/go
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'
      - name: Build
        run: go build -v
      - name: Test
        run: go test -v
      - name: Run
        run: ./test
  java:
    name: Java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/Generator/integration/java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run
        run: java -jar target/test-0.1.0.jar
  php:
    name: PHP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/Generator/integration/php
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run
        run: php main.php
